const products = [
    {
        title: "White Sweater TShirt",
        desc: "Donec sollicitudin molestie malesuada. Vivamus suscipit.",
        price: 15,
        img: "https://i.imgur.com/kiKxz88.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Evening Text Shirt",
        desc: "Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh.",
        price: 20,
        img: "https://i.imgur.com/Qlfua84.jpg",
        categories: ["text"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "White Dress Light",
        desc: "Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam.",
        price: 60,
        img: "https://i.imgur.com/JQVEOEb.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Floral Shirt",
        desc: "Sed porttitor lectus nibh. Sed porttitor lectus.",
        price: 70,
        img: "https://i.imgur.com/Exi1Jr6.jpg",
        categories: ["graphics"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white", "black"],
        inStock: true,
    },
    {
        title: "Black Graphic T Shirt",
        desc: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Nulla quis lorem ut libero malesuada feugiat. Donec sollicitudin molestie malesuada. Proin eget tortor risus.",
        price: 30,
        img: "https://i.imgur.com/vjepNAn.jpg",
        categories: ["graphics"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "Black Text T Shirt",
        desc: "Nulla quis lorem ut libero malesuada feugiat. Curabitur aliquet quam id dui posuere blandit. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
        price: 15,
        img: "https://i.imgur.com/xhZ98Vu.jpg",
        categories: ["text"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "Essentials White T Shirt",
        desc: "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Donec sollicitudin molestie malesuada. Nulla quis lorem ut libero malesuada feugiat. ",
        price: 50,
        img: "https://i.imgur.com/e5WuX5h.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Road T Shirt White",
        desc: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Nulla quis lorem ut libero malesuada feugiat. ",
        price: 20,
        img: "https://i.imgur.com/9gb2cZD.jpg",
        categories: ["graphics"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "White Dress Shirt Formal",
        desc: "Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus",
        price: 50,
        img: "https://i.imgur.com/zIAkxsQ.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Text Black T Shirt Short Sleeve",
        desc: "Donec sollicitudin molestie malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Vivamus suscipit tortor eget felis porttitor volutpat.",
        price: 20,
        img: "https://i.imgur.com/ip0n0Jc.jpg",
        categories: ["text"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "Heart Break T Shirt Graphic",
        desc: "Nulla porttitor accumsan tincidunt. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. ",
        price: 15,
        img: "https://i.imgur.com/3SyQCfH.jpg",
        categories: ["solid", "graphics"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Stylish Black Top",
        desc: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec sollicitudin molestie malesuada. Nulla quis lorem ut libero malesuada feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae",
        price: 40,
        img: "https://i.imgur.com/UcVZzB1.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "Formal Dress Shirt STylish",
        desc: "Nulla quis lorem ut libero malesuada feugiat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
        price: 50,
        img: "https://i.imgur.com/8X8hRZX.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Au Revor T Shirt",
        desc: "Donec sollicitudin molestie malesuada. Donec sollicitudin molestie malesuada. Vivamus magna justo, lacinia ",
        price: 15,
        img: "https://i.imgur.com/evspuDO.jpg",
        categories: ["text"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Graphic Basketball T Shirt Urban",
        desc: "Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt.\n",
        price: 20,
        img: "https://i.imgur.com/hlPS2fc.jpg",
        categories: ["graphics"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["black"],
        inStock: true,
    },
    {
        title: "White Tank T Shirt",
        desc: "Donec sollicitudin molestie malesuada. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. ",
        price: 25,
        img: "https://i.imgur.com/UrURM8J.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["white"],
        inStock: true,
    },
    {
        title: "Grey T Shirt Short Sleeve Casual",
        desc: "Sed porttitor lectus nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget tortor risus.\n",
        price: 15,
        img: "https://i.imgur.com/CEInkLT.jpg",
        categories: ["solid"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["grey"],
        inStock: true,
    },
    {
        title: "Grey Granny Sweater",
        desc: "Donec rutrum congue leo eget malesuada. Proin eget tortor risus.",
        price: 40,
        img: "https://i.imgur.com/96Mvciz.jpg",
        categories: ["text"],
        size: ["XS", "S", "M", "L", "XL"],
        color: ["grey"],
        inStock: true,
    },
];

module.exports = products;